name: asal
description: Prayer time following application.
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ">=2.19.5 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    dio: ^5.1.1
    sembast: ^3.4.4
    cupertino_icons: ^1.0.2
    flutter_bloc: ^8.1.2
    intl: ^0.18.0
    shared_preferences: ^2.1.1
    flutter_easyloading: ^3.0.5
    window_manager: ^0.3.2
    carousel_slider: ^4.2.1
    smooth_page_indicator: ^1.1.0
    google_fonts: ^6.1.0 

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0
    flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/icon.png"

flutter:
    assets:
        - assets/images/
        - assets/icons/
        - assets/google_fonts/
    uses-material-design: true
